In [1]:
import numpy as np

In [2]:
m_21 = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(m_21)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
m_21.ndim

1

In [4]:
m_21.shape

(11,)

In [5]:
n_21 = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(n_21)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [6]:
n_21.ndim

2

In [7]:
n_21.shape

(2, 8)

In [8]:
o_21 = np.array([[[1,2,3,4],[13,14,15,16],[17,18,19,20]],
            [[29,30,31,32],[33,34,35,36],[41,42,43,44]],
            [[8,9,10,11],[20,21,22,23],[67,68,69,70]],
            [[49,50,51,52],[61,62,63,64],[69,70,71,72]]])
print(o_21)

[[[ 1  2  3  4]
  [13 14 15 16]
  [17 18 19 20]]

 [[29 30 31 32]
  [33 34 35 36]
  [41 42 43 44]]

 [[ 8  9 10 11]
  [20 21 22 23]
  [67 68 69 70]]

 [[49 50 51 52]
  [61 62 63 64]
  [69 70 71 72]]]


In [9]:
o_21.ndim

3

In [10]:
o_21.shape

(4, 3, 4)

In [11]:
print(o_21)

[[[ 1  2  3  4]
  [13 14 15 16]
  [17 18 19 20]]

 [[29 30 31 32]
  [33 34 35 36]
  [41 42 43 44]]

 [[ 8  9 10 11]
  [20 21 22 23]
  [67 68 69 70]]

 [[49 50 51 52]
  [61 62 63 64]
  [69 70 71 72]]]


In [12]:
#matrix pertama, baris pertama, kolom keempat
o_21[0,0,3]

4

In [13]:
#matrix pertama, baris kedua, kolom ketiga
o_21[0,1,2]

15

In [14]:
#matrix pertama, baris ketiga, kolom keempat
o_21[0,2,3]

20

In [15]:
#matrix kedua, baris kedua
o_21[1,1,:]

array([33, 34, 35, 36])

In [16]:
#seluruh matrix ketiga 
o_21[2,:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [67, 68, 69, 70]])

In [17]:
#matrix pertama, dan seluruh elemen baris ketiga
o_21[0,2,:]

array([17, 18, 19, 20])

In [18]:
#seluruh elemen kolom ketiga dari semua matrix
o_21[:,:,2]

array([[ 3, 15, 19],
       [31, 35, 43],
       [10, 22, 69],
       [51, 63, 71]])

In [19]:
#matrix pertama, seluruh elemen baris pertama dan elemen baris ketiga
o_21[0,0:3:2]

array([[ 1,  2,  3,  4],
       [17, 18, 19, 20]])

In [20]:
o_21[0,0,0] = 99
#ketika ingin mengubah suatu elemen pada matrix pertama
print(o_21)

[[[99  2  3  4]
  [13 14 15 16]
  [17 18 19 20]]

 [[29 30 31 32]
  [33 34 35 36]
  [41 42 43 44]]

 [[ 8  9 10 11]
  [20 21 22 23]
  [67 68 69 70]]

 [[49 50 51 52]
  [61 62 63 64]
  [69 70 71 72]]]


In [21]:
o_21[0,0,0] = 98
#ketika ingin mengubah suatu elemen pada matrix pertama
print(o_21)

[[[98  2  3  4]
  [13 14 15 16]
  [17 18 19 20]]

 [[29 30 31 32]
  [33 34 35 36]
  [41 42 43 44]]

 [[ 8  9 10 11]
  [20 21 22 23]
  [67 68 69 70]]

 [[49 50 51 52]
  [61 62 63 64]
  [69 70 71 72]]]


In [22]:
np.ones((2,3))
#matriks elemen 1 dengan baris 2 dan kolom 3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((3,5))
#matriks elemen 1 dengan baris 3 dan kolom 5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.zeros((3,2))
#matriks elemen 0 dengan baris 3 dan kolom 2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.zeros((2,5))
#matriks elemen 0 dengan baris 2 dan kolom 5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.identity(3)
#matriks identitas 3 x 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.ones((3,5,4))
#matriks elemen 1 dengan jumlah matriks 3, baris 5, dan kolom 4

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [28]:
np.ones((2,3,5))
#matriks elemen 1 dengan jumlah matriks 2, baris 3, dan kolom 5

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [29]:
np.full((5,3),5)
#matriks elemen 5 dengan baris 5 dan kolom 3

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [30]:
np.random.rand(2,2)
#matriks elemennya random dengan 2 x 2

array([[0.18513787, 0.22198152],
       [0.00838096, 0.99916539]])

In [31]:
np.random.randint(1,15,size=(3,5))
#matriks elemen random bilangan 1-15 dengan baris 3 dan kolom 5

array([[14, 12, 10,  1, 10],
       [ 4, 14, 13,  2,  2],
       [ 1,  7,  1, 13,  6]])

In [32]:
np.random.randint(1,5,size=(5,3))
#matriks elemen random bilangan 1-5 dengan baris 5 dan kolom 3

array([[3, 2, 2],
       [3, 4, 3],
       [3, 2, 4],
       [2, 1, 3],
       [3, 1, 4]])

In [33]:
t_21 = np.zeros((9,9))
print(t_21)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [34]:
t_21 = np.zeros((5,4))
print(t_21)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
i_21 = np.identity(8)
print(i_21)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [36]:
i_21 = np.identity(6)
print(i_21)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [37]:
i_21 = 3*i_21
print(i_21)

[[3. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3.]]


In [38]:
k_21 = np.ones((3,3))
m_21 = np.identity(3)*3
u_21 = k_21+m_21
print(u_21)

[[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]


In [39]:
m_21 = np.array([1,2,3,4,5,6,7,8,9,10])
print(m_21)
print("---------------")
u_21 = m_21
print(u_21)
print("---------------")
u_21[2] = 15
print(u_21)
print("---------------")
print(m_21)

[ 1  2  3  4  5  6  7  8  9 10]
---------------
[ 1  2  3  4  5  6  7  8  9 10]
---------------
[ 1  2 15  4  5  6  7  8  9 10]
---------------
[ 1  2 15  4  5  6  7  8  9 10]


In [40]:
t_21 = np.array([[1,6,9,2,4], [3,5,1,2,4]])
i_21 = np.array([[5,9,6,4,6], [7,1,2,9,8]])

print(t_21)
print(i_21)
print("---------------")
k_21 = t_21 + i_21
print(k_21)
print("---------------")
k_21 = t_21 - i_21
print(k_21)
print("---------------")
k_21 = t_21 * i_21
print(k_21)
print("---------------")
k_21 = t_21**2
print(k_21)

[[1 6 9 2 4]
 [3 5 1 2 4]]
[[5 9 6 4 6]
 [7 1 2 9 8]]
---------------
[[ 6 15 15  6 10]
 [10  6  3 11 12]]
---------------
[[-4 -3  3 -2 -2]
 [-4  4 -1 -7 -4]]
---------------
[[ 5 54 54  8 24]
 [21  5  2 18 32]]
---------------
[[ 1 36 81  4 16]
 [ 9 25  1  4 16]]


In [41]:
s_21 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

v_21 = np.array([[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]])
r_21 = np.array([[2, 1],
                 [2, 3],
                 [3, 2]])

z_21 = s_21 * v_21
print(z_21)
print("===================")
z_21 = np.matmul(s_21, v_21)
print(z_21)
print("===================")
z_21 = np.matmul(v_21, r_21)
print(z_21)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[[ 78  67]
 [ 99  85]
 [120 103]]


In [42]:
v_21 = np.array([[ 3, 15, 19],
                [31, 35, 43],
                [10, 22, 69],
                [51, 63, 71]])
min_21 = np.min(v_21)
max_21 = np.max(v_21)
sum_21 = np.sum(v_21)
print("Nilai minimumnya adalah ", min_21)
print("Nilai maksimumnya adalah ", max_21)
print("Jumlahnya adalah ", sum_21)

print("===================")
min_21 = np.min(v_21)
print(min_21)
min_21 = np.min(v_21, axis=0)
print(min_21)
min_21 = np.min(v_21, axis=1)
print(min_21)
print("===================")
max_21 = np.max(v_21)
print(max_21)
max_21 = np.max(v_21, axis=0)
print(max_21)
max_21 = np.max(v_21, axis=1)
print(max_21)
print("===================")
sum_21 = np.sum(v_21)
print(sum_21)
sum_21 = np.sum(v_21, axis=0)
print(sum_21)
sum_21 = np.sum(v_21, axis=1)
print(sum_21)

Nilai minimumnya adalah  3
Nilai maksimumnya adalah  71
Jumlahnya adalah  432
3
[ 3 15 19]
[ 3 31 10 51]
71
[51 63 71]
[19 43 69 71]
432
[ 95 135 202]
[ 37 109 101 185]
